#!/bin/bash

in_xdr=0
in_f90=0
f90_libs='-lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_def -lpthread' # 64 bits
#f90_libs='-lmkl_sequential -lmkl_core -lmkl_def -lpthread' # ??
#f90_libs='-lmkl_intel -lmkl_sequential -lmkl_core -lpthread -lm' # 32 bits
#f90_libs=-llapack
#f90_opt='-fast'
#f90_opt='-check all'

f2py_exe='none'
if [ $f2py_exe = 'none' ]; then which f2py > /dev/null 2> /dev/null ; if [ $? -eq 0 ]; then f2py_exe=f2py; fi; fi
if [ $f2py_exe = 'none' ]; then which f2py2 > /dev/null 2> /dev/null; if [ $? -eq 0 ]; then f2py_exe=f2py2; fi; fi
if [ $f2py_exe = 'none' ]; then echo "!Error: Install f2py support."; exit; fi


if [ ! -e io_formats/libxdrfile.so ]; then

   in_xdr=1
   echo ' '
   echo '>>>>>> Installing the xdr library...'
   echo '>>>>>> Installing the xdr library...' > INSTALL.log
   tar -zxvf xdrfile-1.1.1.tar.gz 1>/dev/null
   cd xdrfile-1.1.1/
   ./configure --prefix=$PWD/../xdrfiles --enable-fortran F77=ifort --enable-shared 1>> ../INSTALL.log 2>> ../INSTALL.log
   make install 1>> ../INSTALL.log 2>> ../INSTALL.log
   make test >> ../INSTALL.log 2>> ../INSTALL.log
   cd ..
   rm -r xdrfile-1.1.1

   check=0
   grep 'Testing basic xdrfile library: PASSED' INSTALL.log 1>/dev/null
   check=$[$?+$check]
   grep 'Testing xtc functionality: PASSED' INSTALL.log 1>/dev/null
   check=$[$?+$check]
   grep 'Testing trr functionality: PASSED' INSTALL.log 1>/dev/null
   check=$[$?+$check]
   if [ $check -eq 0 ]; then
      cp xdrfiles/lib/libxdrfile.so.4.0.0 io_formats/libxdrfile.so
      rm -r xdrfiles
      echo '> XDR library compiled as io_formats/libxdrfile.so'
   else
      echo '> Error: check the file INSTALL.log'
   fi
   echo ' '

fi

f_files=(pyn_water.f90 pyn_fort_enm.f90 pyn_fort_general.f90 pyn_fort_net.f90 pyn_hbonds.f90 pyn_fort_math.f90)


for ff in ${f_files[*]}; do
    if [ ! -e ${ff%.*}.so ]; then
	in_f90=1
    fi
done

if [ $in_f90 -eq 1 ]; then
    echo ' '
    echo '>>>>>> Compiling the fortran libraries...'
    if [ $in_xdr -eq 1 ]; then
	echo '>>>>>> Compiling the fortran libraries...' >> INSTALL.log
    else
	echo '>>>>>> Compiling the fortran libraries...' > INSTALL.log
    fi
fi

for ff in ${f_files[*]}; do
    if [ ! -e ${ff%.*}.so ]; then
	$f2py_exe --opt=$f90_opt --f90flags=$f90_flags -c -m ${ff%.*} $ff $f90_libs 1>> INSTALL.log 2>> INSTALL.log
	if [ ! -e ${ff%.*}.so ]; then
	    echo '> Error compiling' $ff': check the file INSTALL.log'
	else
	    echo '>' ${ff%.*}.so 'compiled.'
	fi
    fi
done

if [ $in_f90 -eq 1 ]; then
    echo ' '
fi


